export enum ScreenNames {
  LOGIN_PAGE = 'LOGIN_PAGE',
  REGISTRATION_PAGE = 'REGISTRATION_PAGE',
  HOME_PAGE = 'HOME_PAGE',
  FAVORITE_PAGE='FAVORITE_PAGE',
  FILTERS_SETTINGS_PAGE='FILTERS_SETTINGS_PAGE',
  LOGGED_IN_STACK = 'LOGGED_IN_STACK',
  LOGGED_OUT_STACK = 'LOGGED_OUT_STACK',
  TAB_BAR_STACK = 'TAB_BAR_STACK',
  DRAWER_STACK = 'DRAWER_STACK',
  PET_PAGE = 'PET_PAGE',
  LANGUAGES_PAGE = 'LANGUAGES_PAGE',
}